//
//  Modifier.swift
//  Trinkets
//
//  Created by Martônio Júnior on 19/10/2025.
//

/// Atomic mutation that will be performed on a target.
/// 
/// By default, you can use the `Modify` type to create a generic modifier, with
/// this protocol being recommended when the custom operation has data associated with it.
public protocol Modifier<Target, Output> {
    /// Structure to be modified.
    associatedtype Target
    /// Result of the operation.
    /// 
    /// Can be either the result of the operation (success/fail) or a generated by-product (remainder, composed, etc.).
    associatedtype Output = Void
    /// Performs the operation onto a target.
    /// - Parameter target: Target to be modified.
    /// - Returns: Output of the operation.
    func apply(to target: inout Target) -> Output
}

// MARK: Modifier.Target: Optional
public extension Modifier {
    /// Performs the operation onto an unwrapped target.
    /// - Parameter target: Target to be modified.
    /// - Returns: Output of the operation. Returns `nil` when the modified target becomes `nil`.
    func apply<T>(unwrapped target: inout T) -> Output? where Target == T? {
        let result = preview(on: target)

        if let newTarget = result.target {
            target = newTarget
            return result.output
        }

        return nil
    }
}

// MARK: Sequence (EX)
extension Sequence where Element: Modifier, Element.Output == Void {
    /// Performs the operations in sequence order onto a target.
    /// - Parameter target: Target to be modified.
    func apply(to target: inout Element.Target) {
        forEach { $0.apply(to: &target) }
    }
}
